"""empty message

Revision ID: f15b73279c5e
Revises: 9782dd13aa19
Create Date: 2021-08-26 15:08:31.645882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15b73279c5e'
down_revision = '9782dd13aa19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('yest_price', sa.Float(precision=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'yest_price')
    # ### end Alembic commands ###
